BATCH_SIZE: 1
NUM_EPOCHS: 20
NUM_WORKERS: 0
LEARNING_RATE: 0.0001
MAX_SEQ_LEN: 8
LATENT_DIM: 8
DATASET: coco
ARCHITECTURE: resnet18
MASKING: True
LAMBDA_IMAGE: 1.0
LAMBDA_TEXT: 0.01
LAMBDA_KL: 0.0001
WARMUP_EPOCHS: 0 # number of warmup epochs (unmasked training)
CLIP_GRADS: True
CLIP_GRADS_NORM: 1.0
DIFFUSION: True