BATCH_SIZE: 32
NUM_EPOCHS: 50
NUM_WORKERS: 12
LEARNING_RATE: 0.00001
MAX_SEQ_LEN: 8
LATENT_DIM: 4096
DATASET: cifar100
ARCHITECTURE: resnet152
MASKING: True
LAMBDA_IMAGE: 1.0
LAMBDA_TEXT: 0.05
LAMBDA_KL: 0.01
WARMUP_EPOCHS: 0 # number of warmup epochs (unmasked training)
CLIP_GRADS: True
CLIP_GRADS_NORM: 0.1