BATCH_SIZE: 64
NUM_EPOCHS: 500
NUM_WORKERS: 12
LEARNING_RATE: 0.0001
MAX_SEQ_LEN: 8
LATENT_DIM: 1024
DATASET: cifar100
ARCHITECTURE: resnet50
MASKING: True
LAMBDA_IMAGE: 1.0
LAMBDA_TEXT: 0.05
LAMBDA_KL: 0.01
WARMUP_EPOCHS: 0 # number of warmup epochs (unmasked training)