BATCH_SIZE: 128
NUM_EPOCHS: 20
NUM_WORKERS: 12
LEARNING_RATE: 0.0001
MAX_SEQ_LEN: 8
LATENT_DIM: 512
DATASET: cifar10
ARCHITECTURE: resnet18
MASKING: False
LAMBDA_IMAGE: 1.0
LAMBDA_TEXT: 0.0
LAMBDA_KL: 0.0
WARMUP_EPOCHS: 0 # number of warmup epochs (unmasked training)
CLIP_GRADS: False
CLIP_GRADS_NORM: 1.0
DIFFUSION: True
CONDITIONING: concat-mlp
PRETRAINED_IMG_ENC: t2ivae_combined_cifar10_resnet18_img_recon_L2_no_avgpool_latent512_8_22_latest