BATCH_SIZE: 128
NUM_EPOCHS: 20
NUM_WORKERS: 12
LEARNING_RATE: 0.0001
MAX_SEQ_LEN: 8
LATENT_DIM: 1024
DATASET: cifar10
ARCHITECTURE: resnet18
MASKING: False
LAMBDA_IMAGE: 1.0
LAMBDA_TEXT: 0.0
LAMBDA_KL: 0.0
WARMUP_EPOCHS: 10 # number of warmup epochs (unmasked training with resnet)
CLIP_GRADS: False
CLIP_GRADS_NORM: 1.0
DIFFUSION: True
CONDITIONING: concat-mlp