BATCH_SIZE: 32
NUM_EPOCHS: 50
NUM_WORKERS: 12
LEARNING_RATE: 0.0001
MAX_SEQ_LEN: 8
LATENT_DIM: 2048
DATASET: cifar10
ARCHITECTURE: resnet152
MASKING: True
LAMBDA_IMAGE: 1.0
LAMBDA_TEXT: 0.05
LAMBDA_KL: 0.001
WARMUP_EPOCHS: 0 # number of warmup epochs (unmasked training)
CLIP_GRADS: True
CLIP_GRADS_NORM: 1.0